[package]
name = "rubik-cage"
version = "0.1.0"
edition = "2024"

[dependencies]
owo-colors = "4.2.2"
rand = "0.9.2"
getrandom = { version = "0.3", features = ["wasm_js"] }
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
